# Generated by Django 4.2.23 on 2025-08-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0002_remove_team_created_by_team_description_team_manager_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="manager",
        ),
        migrations.AddField(
            model_name="team",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["admin", "manager", "team_lead"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
