# Generated by Django 4.2.23 on 2025-08-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
