# Generated by Django 5.2.4 on 2025-07-24 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_team_lead_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lead",
        ),
    ]
