# Generated by Django 4.2.23 on 2025-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_delete_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("team_lead", "Team Lead"),
                    ("agent", "Agent"),
                    ("custom", "Custom User"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
    ]
