# Generated by Django 4.2.23 on 2025-08-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_remove_team_manager_team_assigned_to"),
        ("users", "0005_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="teams.team",
            ),
        ),
    ]
