# Generated by Django 4.2.23 on 2025-08-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_remove_team_created_by_team_description_team_manager_and_more"),
        ("leads", "0004_lead_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.team",
            ),
        ),
    ]
