# Generated by Django 4.2.23 on 2025-08-07 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0003_remove_team_manager_team_assigned_to"),
        ("leads", "0005_lead_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="author",
            new_name="created_by",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="created_by",
        ),
        migrations.AddField(
            model_name="attachment",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="leads",
            field=models.ManyToManyField(blank=True, to="leads.lead"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="lead",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="leads.lead"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(),
        ),
    ]
